#!/bin/bash

# Installation of Coturn and configuration. The Coturn package is needed to have Nextcloud Talk fonctionning properly. 

sudo apt-get install coturn -y

# Modify the coturn file - start at each reboot

sudo nano /etc/default/coturn

      # Change this setting to have this (no comma) : 

      TURNSERVER_ENABLED=1

# Modify the coturn main config file :

sudo nano /etc/turnserver.conf

# Add these settings to the end of the file. No need to change each line of the original file. 

tls-listening-port=5349
listening-ip=222.222.222.222 # Need to be the IP of the server
listening-ip=127.0.0.1
listening-ip=localhost
relay-ip=222.222.222.222 # Need to be the IP of the server
cert=/home/user-data/ssl/ssl_certificate.pem
pkey=/home/user-data/ssl/ssl_private_key.pem
no-tlsv1
no-tlsv1_1
cipher-list="ECDH+AESGCM:DH+AESGCM" # Personal choice. Change as needed!
#:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AES:RSA+3DES:!ADH:!AECDH:!MD5"

fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=password123 # Change this password by a difficult one!!
realm=cloud.exemple.com # Change "cloud.exemple.com" by your domain
total-quota=100
bps-capacity=0
stale-nonce
no-loopback-peers
no-multicast-peers

# Activate the coturn server :

sudo turnserver -c /etc/turnserver.conf --daemon -v

# Open the 5349 port using UFW

sudo ufw allow 5349

# Install the Talk app in Nextcloud Admin Panel

# At the Talk main setting panel for STUN and TURN server : cloud.exemple.com:5349
# Add your secret key and select "UDP and TCP".  
# Voilà! Have fun!


